# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_auto_20160821_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='article/default.png', upload_to='article/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='notify',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=8),
        ),
        migrations.AlterField(
            model_name='article',
            name='open_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
