# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_auto_20160821_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('message', models.CharField(max_length=255)),
                ('status', models.CharField(editable=False, max_length=10)),
                ('open_date', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='help',
            name='description_android',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='help',
            name='description_ios',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='termsofservice',
            name='description_android',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='termsofservice',
            name='description_ios',
            field=tinymce.models.HTMLField(),
        ),
    ]
