# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0009_auto_20160821_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(default='not_sent', editable=False, max_length=10),
        ),
    ]
