# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 15:35
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0010_auto_20160821_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='help',
            name='description_android',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='help',
            name='description_ios',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='termsofservice',
            name='description_android',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='termsofservice',
            name='description_ios',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
