# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 11:36
from __future__ import unicode_literals

import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0012_auto_20160826_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '記事', 'verbose_name_plural': '記事'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'カテゴリ', 'verbose_name_plural': 'カテゴリ'},
        ),
        migrations.AlterModelOptions(
            name='help',
            options={'verbose_name': 'ヘルプ', 'verbose_name_plural': 'ヘルプ'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': '通知', 'verbose_name_plural': '通知'},
        ),
        migrations.AlterModelOptions(
            name='termsofservice',
            options={'verbose_name': '利用規約', 'verbose_name_plural': '利用規約'},
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='著者'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsapp.Category', verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='article/default.png', null=True, upload_to='article/', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='article',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='article',
            name='notify',
            field=models.CharField(choices=[('yes', 'はい'), ('no', 'いいえ')], default='yes', max_length=8, verbose_name='通知する'),
        ),
        migrations.AlterField(
            model_name='article',
            name='open_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='公開日'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', '下書き'), ('public', '公開')], default='draft', max_length=8, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='category',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='help',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='help',
            name='description_android',
            field=ckeditor.fields.RichTextField(verbose_name='内容 Android'),
        ),
        migrations.AlterField(
            model_name='help',
            name='description_ios',
            field=ckeditor.fields.RichTextField(verbose_name='内容 iOS'),
        ),
        migrations.AlterField(
            model_name='help',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=255, verbose_name='メッセージ'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='open_date',
            field=models.DateTimeField(verbose_name='公開日'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(default='not_sent', editable=False, max_length=10, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=60, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='termsofservice',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='termsofservice',
            name='description_android',
            field=ckeditor.fields.RichTextField(verbose_name='内容 Android'),
        ),
        migrations.AlterField(
            model_name='termsofservice',
            name='description_ios',
            field=ckeditor.fields.RichTextField(verbose_name='内容 iOS'),
        ),
        migrations.AlterField(
            model_name='termsofservice',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
    ]
