# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 08:08
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0013_auto_20160827_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='description_android',
            field=ckeditor.fields.RichTextField(verbose_name='Android用'),
        ),
        migrations.AlterField(
            model_name='help',
            name='description_ios',
            field=ckeditor.fields.RichTextField(verbose_name='iOS用'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('Not sent', '未送信'), ('Sent', '送信済み')], default='Not sent', editable=False, max_length=10, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='termsofservice',
            name='description_android',
            field=ckeditor.fields.RichTextField(verbose_name='Android用'),
        ),
        migrations.AlterField(
            model_name='termsofservice',
            name='description_ios',
            field=ckeditor.fields.RichTextField(verbose_name='iOS用'),
        ),
    ]
