# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0014_auto_20160828_0808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '1) 記事', 'verbose_name_plural': '1) 記事'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '2) カテゴリ', 'verbose_name_plural': '2) カテゴリ'},
        ),
        migrations.AlterModelOptions(
            name='help',
            options={'verbose_name': '4) ヘルプ', 'verbose_name_plural': '4) ヘルプ'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': '3) 通知', 'verbose_name_plural': '3) 通知'},
        ),
        migrations.AlterModelOptions(
            name='termsofservice',
            options={'verbose_name': '5) 利用規約', 'verbose_name_plural': '5) 利用規約'},
        ),
        migrations.AddField(
            model_name='help',
            name='name',
            field=models.CharField(default='ヘルプ', editable=False, max_length=10, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='termsofservice',
            name='name',
            field=models.CharField(default='利用規約', editable=False, max_length=10, verbose_name='名称'),
        ),
    ]
